#!/bin/bash
# Create the per-tenant directories on the shared FS (NFS) and seed the config templates into them.
#
# Same role and layout as production's (weko-k8s) scripts/make_volumes.sh:
#   /fs-nginx/<tenant>       … the whole nginx config → /etc/nginx in the nginx container
#   /fs-shibboleth/<tenant>  … Shibboleth SP config   → /etc/shibboleth in the nginx container
#   /fs-config/<tenant>      … invenio.cfg/uwsgi.ini  → var/instance/conf in web/worker
#   /fs-data/<tenant>        … theme/indextree etc.   → var/instance/data in web/worker
#
# These directories back the static PVs generated by gen-tenant.sh, so run this before the Pods mount them.
#
#   bash provision-nfs.sh [tenants.txt]
set -uo pipefail
cd "$(dirname "$0")"
TFILE="${1:-tenants.txt}"
# defaults to the bundled weko-k8s clone
WEKO_K8S_DIR="${WEKO_K8S_DIR:-../weko-k8s}"
SHIB_TEMPLATE_DIR="${SHIB_TEMPLATE_DIR:-$WEKO_K8S_DIR/deploy/weko/shibboleth_template}"
NGINX_TEMPLATE_DIR="${NGINX_TEMPLATE_DIR:-$WEKO_K8S_DIR/deploy/weko/nginx_template}"
FORCE="${FORCE:-no}"
# Production's weko.conf and nginx.conf are a pair (the log_format uses $shib_mail defined in weko.conf),
# so using only one breaks nginx. With the default (no) the template is not seeded and the image's own
# /etc/nginx (seeded by the initContainer) is used; with yes the production template is seeded.
WEKO_NGINX_SHIB="${WEKO_NGINX_SHIB:-no}"
# busybox tar: -k keeps existing files (non-destructive)
TAROPT="-xkf"; [ "$FORCE" = "yes" ] && TAROPT="-xf"

NFS=$(kubectl get pod -n nfs-system -l app=nfs-provisioner -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
if [ -z "$NFS" ]; then
  echo "ERROR: nfs-provisioner pod not found (apply 60-nfs-server.yaml first)"
  exit 1
fi
echo "nfs server pod = $NFS"

# The nfs-provisioner image has no tar, so a busybox helper Pod that mounts the same export volume is
# used to create the directories and copy the files in.
SEED_POD=weko-nfs-seed
kubectl -n nfs-system delete pod "$SEED_POD" --ignore-not-found >/dev/null 2>&1
kubectl apply -f - >/dev/null <<EOF
apiVersion: v1
kind: Pod
metadata: { name: $SEED_POD, namespace: nfs-system }
spec:
  nodeSelector: { nodeType: DATA }
  restartPolicy: Never
  containers:
  - name: seed
    image: busybox:1.36
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - { name: export-volume, mountPath: /export }
  volumes:
  - name: export-volume
    persistentVolumeClaim: { claimName: nfs-export }
EOF
kubectl -n nfs-system wait --for=condition=ready pod/"$SEED_POD" --timeout=180s || {
  echo "ERROR: seed pod not ready"; exit 1; }
# clean up on exit
trap 'kubectl -n nfs-system delete pod "$SEED_POD" --ignore-not-found >/dev/null 2>&1' EXIT

grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$TFILE" | while read -r NAME DBNAME HOST EMAIL PASS INIT _; do
  echo "=== provision NFS dirs: $NAME (host=$HOST) ==="
  #    Create the per-tenant directories (the mkdir part of production's make_volumes.sh)
  kubectl exec -n nfs-system "$SEED_POD" -- sh -c "
    mkdir -p /export/fs-nginx/$NAME /export/fs-shibboleth/$NAME /export/fs-config/$NAME /export/fs-data/$NAME/tmp &&
    chmod 0777 /export/fs-nginx/$NAME /export/fs-shibboleth/$NAME &&
    chown -R 1000:1000 /export/fs-config/$NAME /export/fs-data/$NAME &&
    chmod -R og+rwx /export/fs-data/$NAME/tmp" 2>&1 | sed 's/^/  /'

  #    Seed the Shibboleth SP config and inject the FQDN (same __WEKO3_VHOST__ sed as production)
  if [ -d "$SHIB_TEMPLATE_DIR" ]; then
    TMP=$(mktemp -d); cp -r "$SHIB_TEMPLATE_DIR"/. "$TMP"/
    sed -i "s/__WEKO3_VHOST__/${HOST}/g" "$TMP"/shibboleth2.xml 2>/dev/null || true
    tar -C "$TMP" -cf - . | kubectl exec -i -n nfs-system "$SEED_POD" -- \
      tar -C "/export/fs-shibboleth/$NAME" $TAROPT - 2>/dev/null
    echo "  seeded /fs-shibboleth/$NAME ($(kubectl exec -n nfs-system "$SEED_POD" -- sh -c "ls /export/fs-shibboleth/$NAME | wc -l" 2>/dev/null | tr -d ' ') files)"
    rm -rf "$TMP"
  else
    echo "  (skip shibboleth: $SHIB_TEMPLATE_DIR not found)"
  fi

  #    Seed the nginx config and inject the FQDN (the Pod's initContainer fills any gaps from the image)
  if [ "$WEKO_NGINX_SHIB" = "yes" ] && [ -d "$NGINX_TEMPLATE_DIR" ]; then
    TMP=$(mktemp -d); cp -r "$NGINX_TEMPLATE_DIR"/. "$TMP"/
    sed -i "s/__WEKO3_VHOST__/${HOST}/g" "$TMP"/conf.d/weko.conf 2>/dev/null || true
    tar -C "$TMP" -cf - . | kubectl exec -i -n nfs-system "$SEED_POD" -- \
      tar -C "/export/fs-nginx/$NAME" $TAROPT - 2>/dev/null
    echo "  seeded /fs-nginx/$NAME ($(kubectl exec -n nfs-system "$SEED_POD" -- sh -c "ls /export/fs-nginx/$NAME | wc -l" 2>/dev/null | tr -d ' ') files)"
    rm -rf "$TMP"
  else
    echo "  (skip nginx template: WEKO_NGINX_SHIB=$WEKO_NGINX_SHIB / using the image's /etc/nginx)"
  fi
done
echo "=== NFS provisioning done ==="
